# Generated by Django 3.0.4 on 2020-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200302_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='artobject',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity'),
        ),
    ]
