# Generated by Django 3.0.3 on 2020-02-19 09:38

from django.db import migrations

def forwards_func(apps, schema_editor):
    artobj_model = apps.get_model("mainapp", "ArtObject")

    product = artobj_model.objects.get(pk=1)
    product.quantity = 2
    product.save()
    product = artobj_model.objects.get(pk=2)
    product.quantity = 5
    product.save()
    product = artobj_model.objects.get(pk=3)
    product.quantity = 1
    product.save()
    product = artobj_model.objects.get(pk=4)
    product.quantity = 3
    product.save()
    product = artobj_model.objects.get(pk=5)
    product.quantity = 6
    product.save()
    product = artobj_model.objects.get(pk=6)
    product.quantity = 10
    product.save()
    product = artobj_model.objects.get(pk=7)
    product.quantity = 4
    product.save()
    product = artobj_model.objects.get(pk=8)
    product.quantity = 7
    product.save()
    product = artobj_model.objects.get(pk=9)
    product.quantity = 11
    product.save()
    

def reverse_func(apps, schema_editor):
    artobj_model = apps.get_model("mainapp", "ArtObject")

    artobj_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_artobject_quantity'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
