# Generated by Django 3.0.4 on 2020-04-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_fill_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='category is active'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='art object is active'),
        ),
    ]
