# Generated by Django 3.0.4 on 2020-03-30 15:55

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_create_debug_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='artshopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='artshopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=authapp.models.expiration_datetime),
        ),
    ]
