# Generated by Django 3.0.4 on 2020-04-06 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200330_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artshopuser',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='age'),
        ),
        migrations.CreateModel(
            name='ArtShopUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='tags')),
                ('aboutMe', models.TextField(blank=True, max_length=512, verbose_name='about me')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Man'), ('F', 'Woman')], max_length=1, verbose_name='sex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
