# Generated by Django 3.0.4 on 2020-04-06 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20200406_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artshopuserprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
