# Generated by Django 3.0.3 on 2020-02-19 11:21

from django.db import migrations
from django.conf import settings

def forward_func(apps, schema_editor):
    if settings.DEBUG:
        try:
            from authapp.models import ArtShopUser
            ArtShopUser.objects.create_superuser(
                "django", "a@a.aa", "geekbrains", age=40
            )
        except:
            print("Can't create superuser for debug")

def reverse_func(apps, schema_editor):
    if settings.DEBUG:
        try:
            from authapp.models import ArtShopUser
            ArtShopUser.objects.delete_superuser(
                "django", "a@a.aa", "geekbrains", age=40
            )
        except:
            print("Can't delete superuser for debug")


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20200406_1103'),
    ]

    operations = [migrations.RunPython(forward_func, reverse_func)]
